{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOH5eX4F0hIOcoSzLi4ClDh",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rameelarustam47/-Assessment-of-KNN-and-Random-Forest-for-Imputing-Missing-Canal-Discharge-Data-/blob/main/MR%20link%20canal.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import files\n",
        "\n",
        "\n",
        "uploaded = files.upload()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 73
        },
        "id": "PCpOsqJVTffF",
        "outputId": "426c8ad6-540a-4052-fc97-a703d2d6bb22"
      },
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-83d040b8-c965-4c29-a282-b600fc25922c\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-83d040b8-c965-4c29-a282-b600fc25922c\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving MR link canal.xlsx to MR link canal (2).xlsx\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "\n",
        "mr_df = pd.read_excel(\"MR link canal.xlsx\", header=None)\n",
        "\n",
        "\n",
        "print(mr_df.head(10))\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "5QyCBXwqaJff",
        "outputId": "8e0ddacc-c7ca-4a7c-ff32-92351f76ebe6"
      },
      "execution_count": 50,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "    0            1                    2                       3           4  \\\n",
            "0 NaN          NaN                  NaN                     NaN         NaN   \n",
            "1 NaN  channel_nme       recording_date  designed_discharge_msr  head_guage   \n",
            "2 NaN          NaN  2013-01-01 00:00:00                     NaN         NaN   \n",
            "3 NaN          NaN  2013-01-02 00:00:00                     NaN         NaN   \n",
            "4 NaN          NaN  2013-01-03 00:00:00                     NaN         NaN   \n",
            "5 NaN          NaN  2013-01-04 00:00:00                     NaN         NaN   \n",
            "6 NaN          NaN  2013-01-05 00:00:00                     NaN         NaN   \n",
            "7 NaN          NaN  2013-01-06 00:00:00                     NaN         NaN   \n",
            "8 NaN          NaN  2013-01-07 00:00:00                     NaN         NaN   \n",
            "9 NaN          NaN  2013-01-08 00:00:00                     NaN         NaN   \n",
            "\n",
            "                5       6                      7           8               9  \n",
            "0             NaN     NaN                    NaN         NaN             NaN  \n",
            "1  head_discharge  indent  authorized_tail_gauge  tail_gauge  tail_discharge  \n",
            "2             NaN     NaN                    NaN         NaN             NaN  \n",
            "3             NaN     NaN                    NaN         NaN             NaN  \n",
            "4             NaN     NaN                    NaN         NaN             NaN  \n",
            "5             NaN     NaN                    NaN         NaN             NaN  \n",
            "6             NaN     NaN                    NaN         NaN             NaN  \n",
            "7             NaN     NaN                    NaN         NaN             NaN  \n",
            "8             NaN     NaN                    NaN         NaN             NaN  \n",
            "9             NaN     NaN                    NaN         NaN             NaN  \n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "mr_df = pd.read_excel(\"MR link canal.xlsx\", header=None)\n",
        "\n",
        "# Step 2: Set proper header (row index 1)\n",
        "mr_df.columns = mr_df.iloc[1]  # row 1 is the header\n",
        "mr_df = mr_df.drop([0, 1])     # drop the empty first row and header row\n",
        "mr_df = mr_df.reset_index(drop=True)\n",
        "\n",
        "# Step 3: Convert date column to datetime\n",
        "mr_df['recording_date'] = pd.to_datetime(mr_df['recording_date'], errors='coerce')\n",
        "\n",
        "# Step 4: Set date as index\n",
        "mr_df = mr_df.set_index('recording_date')\n",
        "\n",
        "# Step 5: Convert head/tail discharge to numeric\n",
        "cols = ['head_discharge', 'tail_discharge']\n",
        "for col in cols:\n",
        "    mr_df[col] = pd.to_numeric(mr_df[col], errors='coerce')\n",
        "\n",
        "# Step 6: Check the cleaned dataframe\n",
        "print(mr_df.head())\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "s9aIMdKAamSo",
        "outputId": "9e3c95a4-a048-475b-8e32-67fc03540414"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "1               NaN channel_nme designed_discharge_msr head_guage  \\\n",
            "recording_date                                                      \n",
            "2013-01-01      NaN         NaN                    NaN        NaN   \n",
            "2013-01-02      NaN         NaN                    NaN        NaN   \n",
            "2013-01-03      NaN         NaN                    NaN        NaN   \n",
            "2013-01-04      NaN         NaN                    NaN        NaN   \n",
            "2013-01-05      NaN         NaN                    NaN        NaN   \n",
            "\n",
            "1               head_discharge indent authorized_tail_gauge tail_gauge  \\\n",
            "recording_date                                                           \n",
            "2013-01-01                 NaN    NaN                   NaN        NaN   \n",
            "2013-01-02                 NaN    NaN                   NaN        NaN   \n",
            "2013-01-03                 NaN    NaN                   NaN        NaN   \n",
            "2013-01-04                 NaN    NaN                   NaN        NaN   \n",
            "2013-01-05                 NaN    NaN                   NaN        NaN   \n",
            "\n",
            "1               tail_discharge  \n",
            "recording_date                  \n",
            "2013-01-01                 NaN  \n",
            "2013-01-02                 NaN  \n",
            "2013-01-03                 NaN  \n",
            "2013-01-04                 NaN  \n",
            "2013-01-05                 NaN  \n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# =========================================================\n",
        "# STEP 0: Install required packages (run once)\n",
        "# =========================================================\n",
        "!pip install scikit-learn --quiet\n",
        "\n",
        "# =========================================================\n",
        "# STEP 1: Import libraries\n",
        "# =========================================================\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "from sklearn.impute import KNNImputer\n",
        "from sklearn.experimental import enable_iterative_imputer  # noqa\n",
        "from sklearn.impute import IterativeImputer\n",
        "from sklearn.ensemble import RandomForestRegressor\n",
        "\n",
        "from sklearn.preprocessing import MinMaxScaler\n",
        "from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error\n",
        "\n",
        "# =========================================================\n",
        "# STEP 2: Load MR Link Canal Excel file\n",
        "# =========================================================\n",
        "data = pd.read_excel(\"MR link canal.xlsx\", header=None)\n",
        "\n",
        "# Fix headers\n",
        "data.columns = data.iloc[1]\n",
        "data = data.drop(index=[0, 1]).reset_index(drop=True)\n",
        "\n",
        "# Keep relevant columns\n",
        "cols = ['recording_date', 'head_discharge', 'tail_discharge']\n",
        "mr = data[cols].copy()\n",
        "\n",
        "# =========================================================\n",
        "# STEP 3: Data type conversion\n",
        "# =========================================================\n",
        "mr['recording_date'] = pd.to_datetime(mr['recording_date'])\n",
        "mr['head_discharge'] = pd.to_numeric(mr['head_discharge'], errors='coerce')\n",
        "mr['tail_discharge'] = pd.to_numeric(mr['tail_discharge'], errors='coerce')\n",
        "\n",
        "mr = mr.set_index('recording_date')\n",
        "\n",
        "# =========================================================\n",
        "# STEP 4: Time-based interpolation (REFERENCE)\n",
        "# =========================================================\n",
        "mr_interp = mr.interpolate(method='time').bfill().ffill()\n",
        "\n",
        "# =========================================================\n",
        "# STEP 5: Scaling (Min-Max)\n",
        "# =========================================================\n",
        "scaler = MinMaxScaler()\n",
        "mr_scaled = pd.DataFrame(\n",
        "    scaler.fit_transform(mr),\n",
        "    columns=mr.columns,\n",
        "    index=mr.index\n",
        ")\n",
        "\n",
        "# =========================================================\n",
        "# STEP 6: KNN Imputation (on scaled data)\n",
        "# =========================================================\n",
        "knn = KNNImputer(n_neighbors=5)\n",
        "mr_knn_scaled = pd.DataFrame(\n",
        "    knn.fit_transform(mr_scaled),\n",
        "    columns=mr_scaled.columns,\n",
        "    index=mr_scaled.index\n",
        ")\n",
        "\n",
        "# Inverse scaling\n",
        "mr_knn = pd.DataFrame(\n",
        "    scaler.inverse_transform(mr_knn_scaled),\n",
        "    columns=mr.columns,\n",
        "    index=mr.index\n",
        ")\n",
        "\n",
        "# =========================================================\n",
        "# STEP 7: Random Forest Imputation (Iterative Imputer)\n",
        "# =========================================================\n",
        "rf = RandomForestRegressor(\n",
        "    n_estimators=100,\n",
        "    random_state=42,\n",
        "    n_jobs=-1\n",
        ")\n",
        "\n",
        "iter_imputer = IterativeImputer(\n",
        "    estimator=rf,\n",
        "    max_iter=20,\n",
        "    random_state=42\n",
        ")\n",
        "\n",
        "mr_rf_scaled = pd.DataFrame(\n",
        "    iter_imputer.fit_transform(mr_scaled),\n",
        "    columns=mr_scaled.columns,\n",
        "    index=mr_scaled.index\n",
        ")\n",
        "\n",
        "# Inverse scaling\n",
        "mr_rf = pd.DataFrame(\n",
        "    scaler.inverse_transform(mr_rf_scaled),\n",
        "    columns=mr.columns,\n",
        "    index=mr.index\n",
        ")\n",
        "\n",
        "# =========================================================\n",
        "# STEP 8: Metric function\n",
        "# =========================================================\n",
        "def calc_metrics(true, pred):\n",
        "    r2 = r2_score(true, pred)\n",
        "    rmse = np.sqrt(mean_squared_error(true, pred))\n",
        "    mae = mean_absolute_error(true, pred)\n",
        "    mape = np.mean(np.abs((true - pred) / true)) * 100\n",
        "    pearson = np.corrcoef(true, pred)[0, 1]\n",
        "    return r2, rmse, mae, mape, pearson\n",
        "\n",
        "# =========================================================\n",
        "# STEP 9: Calculate metrics (vs interpolation)\n",
        "# =========================================================\n",
        "for col in ['head_discharge', 'tail_discharge']:\n",
        "    print(f\"\\n{col.upper()} discharge metrics:\")\n",
        "\n",
        "    r2, rmse, mae, mape, r = calc_metrics(mr_interp[col], mr_knn[col])\n",
        "    print(f\"KNN_vs_Interp: \"\n",
        "          f\"R²={r2:.4f}, RMSE={rmse:.2f}, MAE={mae:.2f}, \"\n",
        "          f\"MAPE={mape:.2f}%, Pearson r={r:.4f}\")\n",
        "\n",
        "    r2, rmse, mae, mape, r = calc_metrics(mr_interp[col], mr_rf[col])\n",
        "    print(f\"RF_vs_Interp:  \"\n",
        "          f\"R²={r2:.4f}, RMSE={rmse:.2f}, MAE={mae:.2f}, \"\n",
        "          f\"MAPE={mape:.2f}%, Pearson r={r:.4f}\")\n",
        "\n",
        "# =========================================================\n",
        "# STEP 10: Save imputed results (optional)\n",
        "# =========================================================\n",
        "mr_out = mr.copy()\n",
        "mr_out['head_knn'] = mr_knn['head_discharge']\n",
        "mr_out['tail_knn'] = mr_knn['tail_discharge']\n",
        "mr_out['head_rf'] = mr_rf['head_discharge']\n",
        "mr_out['tail_rf'] = mr_rf['tail_discharge']\n",
        "\n",
        "mr_out.to_excel(\"MR_Link_Canal_Imputed.xlsx\")\n",
        "print(\"\\nImputed file saved as MR_Link_Canal_Imputed.xlsx\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "hJJgQv-dvcR_",
        "outputId": "4ca22787-4bde-41f8-8c84-8e383c745be6"
      },
      "execution_count": 51,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.\n",
            "  warnings.warn(\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "HEAD_DISCHARGE discharge metrics:\n",
            "KNN_vs_Interp: R²=-0.5421, RMSE=7721.62, MAE=5854.11, MAPE=150.93%, Pearson r=0.5828\n",
            "RF_vs_Interp:  R²=0.8457, RMSE=2442.65, MAE=1527.73, MAPE=36.69%, Pearson r=0.9228\n",
            "\n",
            "TAIL_DISCHARGE discharge metrics:\n",
            "KNN_vs_Interp: R²=-0.4109, RMSE=5096.13, MAE=3811.23, MAPE=58.52%, Pearson r=0.1844\n",
            "RF_vs_Interp:  R²=-1.4427, RMSE=6705.43, MAE=5026.74, MAPE=49.77%, Pearson r=0.5913\n",
            "\n",
            "Imputed file saved as MR_Link_Canal_Imputed.xlsx\n"
          ]
        }
      ]
    }
  ]
}